# Generated by Django 4.2.29 on 2026-03-09 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('MOTOR', 'Motor'), ('HEALTH', 'Health'), ('LIFE', 'Life'), ('PROPERTY', 'Property'), ('TRAVEL', 'Travel'), ('MARINE', 'Marine'), ('LIABILITY', 'Liability'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('comparison_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurers', models.ManyToManyField(blank=True, related_name='quotes', to='insurers.insurer')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
