# Generated by Django 4.2.29 on 2026-03-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='product_type',
            field=models.CharField(choices=[('MOTOR', 'Motor Insurance'), ('BUSINESS', 'Business Insurance'), ('HEALTH', 'Health Insurance'), ('LIFE', 'Life Insurance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUBMITTED', 'Submitted'), ('IN_DISCUSSION', 'In Discussion'), ('HOLD', 'Hold'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='NEW', max_length=20),
        ),
    ]
